name: Check Cat Listings

on:
  schedule:
    - cron: '5 9 * * *'
    - cron: '0 11 * * *'
    - cron: '0 14 * * *'
    - cron: '0 16 * * *'
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  check-cat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run script
        run: python check_cat_listings.py

      - name: Commit results if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add cat_matches_log.txt
          git commit -m "Update results" || echo "No changes to commit"
          git push
